version: "1,0"
services:
  jupyter-lab:
    build: .
    ports:  
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ./local_workspace:/cont_workspace
    environment:
      - DISPLAY=host.docker.internal:0.0  # X forwarding to Windows host
    deploy:
      resources:
        reservations:
          devices: 
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: IRIDE_SNOW_COVER_2

